sudo: false
language: node_js

node_js:
- '9'

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_install:
- npm update

install:
- npm install
- npm install jest

script: 
- npm test
- npm run test:coverage 

deploy:
  provider: gae
  keyfile: "sw-testint-assignment3-088c548f2fce.json"
  project: "sw-testint-assignment3"
